"""Docker environment setup — configuration generator for deployment.

Generates Dockerfiles, docker-compose configs, environment variables,
and resource limits for each QuantFund V8 deployment environment:
local_research, paper_trading, and live_trading.

This module is a pure configuration generator.  It does not call the
Docker API; the output is consumed by external deployment tooling.
"""

import logging
import textwrap
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

VALID_ENVIRONMENTS = ("local_research", "paper_trading", "live_trading")

# Base Python image used across all environments.
_BASE_IMAGE = "python:3.11-slim"


class DockerEnvironmentSetup:
    """Generate Docker deployment configurations per environment.

    Usage:
        setup = DockerEnvironmentSetup(config)
        dockerfile = setup.generate_dockerfile("paper_trading")
        compose = setup.generate_compose_config("paper_trading")
    """

    def __init__(self, config: Optional[dict] = None) -> None:
        """Initialize with optional configuration overrides.

        Args:
            config: Environment settings typically loaded from
                    system_config.yaml.  Recognised keys:

                    - ``environment``  – default environment name
                    - ``base_image``   – override the base Docker image
                    - ``data_root``    – host path for data volume mounts
                    - ``output_root``  – host path for output volume mounts
                    - ``log_level``    – application log level
                    - ``timezone``     – e.g. America/New_York
                    - ``base_currency``– e.g. USD
        """
        self._config: dict = config or {}
        self._base_image: str = self._config.get("base_image", _BASE_IMAGE)
        logger.info(
            "DockerEnvironmentSetup initialized environment=%s",
            self._config.get("environment", "not set"),
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_dockerfile(self, environment: str) -> str:
        """Generate Dockerfile content for *environment*.

        Args:
            environment: One of local_research, paper_trading, live_trading.

        Returns:
            Multi-line string containing the complete Dockerfile.

        Raises:
            ValueError: If *environment* is not recognised.
        """
        self._assert_valid_environment(environment)

        env_vars = self.get_environment_variables(environment)
        required_services = self.get_required_services(environment)
        healthcheck = self.generate_healthcheck_config()

        # Build the ENV block --------------------------------------------------
        env_lines = "\n".join(
            f"ENV {key}={value}" for key, value in sorted(env_vars.items())
        )

        # Extra system packages needed for certain services --------------------
        extra_packages: List[str] = []
        if "postgres" in required_services:
            extra_packages.append("libpq-dev")
        if "redis" in required_services:
            extra_packages.append("redis-tools")

        apt_install = ""
        if extra_packages:
            pkgs = " ".join(extra_packages)
            apt_install = (
                f"RUN apt-get update && apt-get install -y --no-install-recommends "
                f"{pkgs} && rm -rf /var/lib/apt/lists/*"
            )

        # Monitoring extras for live environments -----------------------------
        monitoring_install = ""
        if environment == "live_trading":
            monitoring_install = "RUN pip install --no-cache-dir prometheus-client sentry-sdk"

        # Healthcheck ----------------------------------------------------------
        hc = healthcheck
        hc_cmd = (
            f'HEALTHCHECK --interval={hc["interval"]} '
            f'--timeout={hc["timeout"]} '
            f'--start-period={hc["start_period"]} '
            f'--retries={hc["retries"]} \\\n'
            f'  CMD {hc["test"]}'
        )

        dockerfile = textwrap.dedent(f"""\
            # QuantFund V8 — {environment}
            # Auto-generated by DockerEnvironmentSetup
            FROM {self._base_image}

            WORKDIR /app

            {apt_install}

            COPY requirements.txt .
            RUN pip install --no-cache-dir -r requirements.txt

            {monitoring_install}

            COPY . .

            {env_lines}

            {hc_cmd}

            EXPOSE 8000

            CMD ["python", "-m", "quant_fund.main"]
        """)

        # Collapse multiple blank lines that may appear from empty blocks.
        while "\n\n\n" in dockerfile:
            dockerfile = dockerfile.replace("\n\n\n", "\n\n")

        logger.debug("Generated Dockerfile for %s (%d bytes)", environment, len(dockerfile))
        return dockerfile

    def generate_compose_config(self, environment: str) -> dict:
        """Generate a docker-compose configuration dict for *environment*.

        Args:
            environment: One of local_research, paper_trading, live_trading.

        Returns:
            Dict suitable for serialising to docker-compose.yaml.

        Raises:
            ValueError: If *environment* is not recognised.
        """
        self._assert_valid_environment(environment)

        services: Dict[str, dict] = {}
        required = self.get_required_services(environment)
        resource_limits = self.get_resource_limits(environment)
        env_vars = self.get_environment_variables(environment)
        healthcheck = self.generate_healthcheck_config()

        data_root = self._config.get("data_root", "./data")
        output_root = self._config.get("output_root", "./output")

        # Main application service ---------------------------------------------
        app_service: dict = {
            "build": {"context": ".", "dockerfile": "Dockerfile"},
            "environment": env_vars,
            "volumes": [
                f"{data_root}:/app/data",
                f"{output_root}:/app/output",
            ],
            "ports": ["8000:8000"],
            "deploy": {
                "resources": {
                    "limits": {
                        "cpus": str(resource_limits["cpus"]),
                        "memory": resource_limits["memory"],
                    },
                },
            },
            "healthcheck": {
                "test": healthcheck["test"],
                "interval": healthcheck["interval"],
                "timeout": healthcheck["timeout"],
                "start_period": healthcheck["start_period"],
                "retries": healthcheck["retries"],
            },
            "restart": "unless-stopped",
        }

        depends_on: List[str] = []

        # Database service -----------------------------------------------------
        if "postgres" in required:
            services["postgres"] = {
                "image": "postgres:16-alpine",
                "environment": {
                    "POSTGRES_DB": "quantfund",
                    "POSTGRES_USER": "quantfund",
                    "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD:-quantfund}",
                },
                "volumes": ["pgdata:/var/lib/postgresql/data"],
                "ports": ["5432:5432"],
                "restart": "unless-stopped",
            }
            depends_on.append("postgres")

        # Redis service --------------------------------------------------------
        if "redis" in required:
            services["redis"] = {
                "image": "redis:7-alpine",
                "ports": ["6379:6379"],
                "restart": "unless-stopped",
            }
            depends_on.append("redis")

        # Monitoring stack -----------------------------------------------------
        if "prometheus" in required:
            services["prometheus"] = {
                "image": "prom/prometheus:latest",
                "volumes": ["./prometheus.yml:/etc/prometheus/prometheus.yml"],
                "ports": ["9090:9090"],
                "restart": "unless-stopped",
            }
            depends_on.append("prometheus")

        if "grafana" in required:
            services["grafana"] = {
                "image": "grafana/grafana:latest",
                "ports": ["3000:3000"],
                "depends_on": ["prometheus"],
                "restart": "unless-stopped",
            }

        # Broker adapter service -----------------------------------------------
        if "broker_adapter" in required:
            broker_image = (
                "quantfund/broker-sim:latest"
                if environment == "paper_trading"
                else "quantfund/broker-live:latest"
            )
            services["broker_adapter"] = {
                "image": broker_image,
                "environment": {
                    "BROKER_MODE": "simulation" if environment == "paper_trading" else "live",
                },
                "ports": ["8001:8001"],
                "restart": "unless-stopped",
            }
            depends_on.append("broker_adapter")

        if depends_on:
            app_service["depends_on"] = depends_on

        services["app"] = app_service

        # Build the top-level compose structure --------------------------------
        compose: dict = {
            "version": "3.8",
            "services": services,
            "volumes": {},
        }

        if "postgres" in required:
            compose["volumes"]["pgdata"] = {"driver": "local"}

        logger.debug("Generated compose config for %s with %d services",
                      environment, len(services))
        return compose

    def get_environment_variables(self, environment: str) -> dict:
        """Return environment variables for *environment*.

        Args:
            environment: One of local_research, paper_trading, live_trading.

        Returns:
            Dict of env-var name to value.

        Raises:
            ValueError: If *environment* is not recognised.
        """
        self._assert_valid_environment(environment)

        log_level = self._config.get("log_level", "INFO")
        timezone = self._config.get("timezone", "America/New_York")
        base_currency = self._config.get("base_currency", "USD")

        common: dict = {
            "QUANTFUND_ENV": environment,
            "LOG_LEVEL": log_level,
            "TZ": timezone,
            "BASE_CURRENCY": base_currency,
            "PYTHONUNBUFFERED": "1",
        }

        if environment == "local_research":
            common.update({
                "BROKER_ENABLED": "false",
                "MONITORING_ENABLED": "false",
                "DATA_SOURCE": "local",
            })

        elif environment == "paper_trading":
            common.update({
                "BROKER_ENABLED": "true",
                "BROKER_MODE": "simulation",
                "MONITORING_ENABLED": "true",
                "DATA_SOURCE": "remote",
                "REDIS_URL": "redis://redis:6379/0",
                "DATABASE_URL": "postgresql://quantfund:quantfund@postgres:5432/quantfund",
            })

        elif environment == "live_trading":
            common.update({
                "BROKER_ENABLED": "true",
                "BROKER_MODE": "live",
                "MONITORING_ENABLED": "true",
                "DATA_SOURCE": "remote",
                "REDIS_URL": "redis://redis:6379/0",
                "DATABASE_URL": "postgresql://quantfund:quantfund@postgres:5432/quantfund",
                "SENTRY_DSN": "${SENTRY_DSN}",
                "PROMETHEUS_PUSH_GATEWAY": "http://prometheus:9091",
                "KILL_SWITCH_ENABLED": "true",
                "RISK_CHECKS_STRICT": "true",
            })

        logger.debug("Environment variables for %s: %d vars", environment, len(common))
        return common

    def get_resource_limits(self, environment: str) -> dict:
        """Return CPU and memory resource limits for *environment*.

        Args:
            environment: One of local_research, paper_trading, live_trading.

        Returns:
            Dict with keys ``cpus``, ``memory``, ``memory_reservation``,
            and ``pids_limit``.

        Raises:
            ValueError: If *environment* is not recognised.
        """
        self._assert_valid_environment(environment)

        limits: Dict[str, dict] = {
            "local_research": {
                "cpus": 2.0,
                "memory": "4g",
                "memory_reservation": "2g",
                "pids_limit": 256,
            },
            "paper_trading": {
                "cpus": 4.0,
                "memory": "8g",
                "memory_reservation": "4g",
                "pids_limit": 512,
            },
            "live_trading": {
                "cpus": 8.0,
                "memory": "16g",
                "memory_reservation": "8g",
                "pids_limit": 1024,
            },
        }

        result = limits[environment]
        logger.debug("Resource limits for %s: %s", environment, result)
        return result

    def validate_environment(self, environment: str) -> Tuple[bool, List[str]]:
        """Validate that the environment configuration is consistent.

        Checks include:
        - Environment name is recognised.
        - Required config keys are present for the target environment.
        - Resource limits are within safe bounds.
        - Live-trading guards (kill switch, strict risk checks).

        Args:
            environment: The environment name to validate.

        Returns:
            Tuple of (is_valid, issues) where *issues* is a list of
            human-readable problem descriptions.  Empty when valid.
        """
        issues: List[str] = []

        # 1. Environment name --------------------------------------------------
        if environment not in VALID_ENVIRONMENTS:
            issues.append(
                f"Unknown environment '{environment}'. "
                f"Must be one of {VALID_ENVIRONMENTS}."
            )
            return False, issues

        # 2. Required config keys ----------------------------------------------
        if environment in ("paper_trading", "live_trading"):
            if not self._config.get("timezone"):
                issues.append("Config missing 'timezone' (required for trading environments).")
            if not self._config.get("base_currency"):
                issues.append("Config missing 'base_currency' (required for trading environments).")

        # 3. Resource limit sanity ---------------------------------------------
        limits = self.get_resource_limits(environment)
        if limits["cpus"] < 1.0:
            issues.append(f"CPU limit ({limits['cpus']}) is below minimum of 1.0.")

        # 4. Live-trading guards -----------------------------------------------
        if environment == "live_trading":
            env_vars = self.get_environment_variables(environment)
            if env_vars.get("KILL_SWITCH_ENABLED") != "true":
                issues.append("Kill switch must be enabled for live trading.")
            if env_vars.get("RISK_CHECKS_STRICT") != "true":
                issues.append("Strict risk checks must be enabled for live trading.")
            if env_vars.get("MONITORING_ENABLED") != "true":
                issues.append("Monitoring must be enabled for live trading.")

        is_valid = len(issues) == 0
        if is_valid:
            logger.info("Environment '%s' validation passed.", environment)
        else:
            logger.warning(
                "Environment '%s' validation failed with %d issue(s).",
                environment,
                len(issues),
            )
        return is_valid, issues

    def get_required_services(self, environment: str) -> List[str]:
        """Return the list of required backing services for *environment*.

        Args:
            environment: One of local_research, paper_trading, live_trading.

        Returns:
            Sorted list of service names (e.g. ``["postgres", "redis"]``).

        Raises:
            ValueError: If *environment* is not recognised.
        """
        self._assert_valid_environment(environment)

        services_map: Dict[str, List[str]] = {
            "local_research": [
                "postgres",
            ],
            "paper_trading": [
                "postgres",
                "redis",
                "broker_adapter",
            ],
            "live_trading": [
                "postgres",
                "redis",
                "broker_adapter",
                "prometheus",
                "grafana",
            ],
        }

        result = sorted(services_map[environment])
        logger.debug("Required services for %s: %s", environment, result)
        return result

    def generate_healthcheck_config(self) -> dict:
        """Return a Docker healthcheck configuration dict.

        Returns:
            Dict with keys ``test``, ``interval``, ``timeout``,
            ``start_period``, and ``retries``.
        """
        config: dict = {
            "test": "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\"",
            "interval": "30s",
            "timeout": "10s",
            "start_period": "40s",
            "retries": 3,
        }
        logger.debug("Generated healthcheck config")
        return config

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _assert_valid_environment(self, environment: str) -> None:
        """Raise ``ValueError`` if *environment* is not recognised."""
        if environment not in VALID_ENVIRONMENTS:
            raise ValueError(
                f"Invalid environment '{environment}'. "
                f"Must be one of {VALID_ENVIRONMENTS}."
            )
