"""Feature combinator for automated signal candidate generation.

Generates candidate signal expressions by combining existing features:
linear combinations, ratio features, and interaction terms.
"""

import logging
from dataclasses import dataclass, field
from typing import List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class CandidateSignal:
    """A candidate signal generated by combining features."""

    name: str
    expression: str
    values: pd.Series
    component_features: List[str] = field(default_factory=list)


class FeatureCombinator:
    """Generates candidate signals from existing feature columns.

    Produces linear combinations, ratio features, and interaction terms.
    All operations are cross-sectional (across tickers at a single point in time).
    """

    def __init__(self, config: Optional[dict] = None):
        cfg = config or {}
        self._n_random_combos = cfg.get("n_random_combinations", 50)
        self._seed = cfg.get("random_seed", 42)

    def generate_candidates(
        self,
        feature_matrix: pd.DataFrame,
        regime_labels: Optional[pd.Series] = None,
    ) -> List[CandidateSignal]:
        """Generate candidate signals from a feature matrix.

        Args:
            feature_matrix: DataFrame indexed by ticker, columns are features.
                Must be pre-normalised.
            regime_labels: Optional Series of regime labels indexed by ticker
                for interaction terms.

        Returns:
            List of CandidateSignal objects.
        """
        candidates: List[CandidateSignal] = []
        cols = list(feature_matrix.columns)

        if len(cols) < 2:
            return candidates

        candidates.extend(self._generate_linear_combinations(feature_matrix, cols))
        candidates.extend(self._generate_ratio_features(feature_matrix, cols))
        if regime_labels is not None:
            candidates.extend(
                self._generate_interaction_terms(feature_matrix, cols, regime_labels)
            )

        return candidates

    def _generate_linear_combinations(
        self, fm: pd.DataFrame, cols: List[str]
    ) -> List[CandidateSignal]:
        """Random linear combinations with coefficients from [-1, 1]."""
        rng = np.random.default_rng(self._seed)
        candidates = []
        n_combos = min(self._n_random_combos, len(cols) * (len(cols) - 1) // 2)

        for i in range(n_combos):
            n_terms = rng.integers(2, min(5, len(cols)) + 1)
            selected = rng.choice(cols, size=n_terms, replace=False)
            weights = rng.uniform(-1, 1, size=n_terms)

            values = pd.Series(0.0, index=fm.index)
            expr_parts = []
            for col, w in zip(selected, weights):
                values += w * fm[col].fillna(0.0)
                expr_parts.append(f"{w:.3f}*{col}")

            name = f"linear_combo_{i}"
            candidates.append(
                CandidateSignal(
                    name=name,
                    expression=" + ".join(expr_parts),
                    values=values,
                    component_features=list(selected),
                )
            )
        return candidates

    def _generate_ratio_features(
        self, fm: pd.DataFrame, cols: List[str]
    ) -> List[CandidateSignal]:
        """Pairwise ratio features: feature_A / feature_B."""
        candidates = []
        rng = np.random.default_rng(self._seed + 1)
        max_ratios = min(self._n_random_combos, len(cols) * (len(cols) - 1))
        pairs = []
        for a in cols:
            for b in cols:
                if a != b:
                    pairs.append((a, b))

        if len(pairs) > max_ratios:
            indices = rng.choice(len(pairs), size=max_ratios, replace=False)
            pairs = [pairs[i] for i in indices]

        for a, b in pairs:
            denom = fm[b].fillna(0.0)
            safe_denom = denom.where(denom.abs() > 1e-8, np.nan)
            values = fm[a].fillna(0.0) / safe_denom

            name = f"ratio_{a}_over_{b}"
            candidates.append(
                CandidateSignal(
                    name=name,
                    expression=f"{a} / {b}",
                    values=values,
                    component_features=[a, b],
                )
            )
        return candidates

    def _generate_interaction_terms(
        self,
        fm: pd.DataFrame,
        cols: List[str],
        regime_labels: pd.Series,
    ) -> List[CandidateSignal]:
        """Feature × regime_label interaction terms."""
        candidates = []
        aligned_regime = regime_labels.reindex(fm.index).fillna(0.0)

        for col in cols:
            values = fm[col].fillna(0.0) * aligned_regime
            name = f"interact_{col}_x_regime"
            candidates.append(
                CandidateSignal(
                    name=name,
                    expression=f"{col} * regime_label",
                    values=values,
                    component_features=[col],
                )
            )
        return candidates
